name: build
on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Maven
        run: mvn --batch-mode package
      - run: ls target/*jar
      - run: mkdir lambda
      - run: unzip target/badge*jar -d lambda
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Deploy Lambda function via S3
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: read-openbadges-metadata
          code-artifacts-dir: lambda
          handler: "com.pigumer.BadgeHandler::handleRequest"
          runtime: java21
          architectures: arm64
          s3-bucket: sslabhnd

